//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbpCodeGeneration.VisualStudio.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbpCodeGeneration.VisualStudio.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Service.
        /// </summary>
        public static string applicationservice {
            get {
                return ResourceManager.GetString("applicationservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute name.
        /// </summary>
        public static string attributename {
            get {
                return ResourceManager.GetString("attributename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string basic {
            get {
                return ResourceManager.GetString("basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class name.
        /// </summary>
        public static string classname {
            get {
                return ResourceManager.GetString("classname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class primary key.
        /// </summary>
        public static string classprimarykey {
            get {
                return ResourceManager.GetString("classprimarykey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string controller {
            get {
                return ResourceManager.GetString("controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Service.
        /// </summary>
        public static string domainservice {
            get {
                return ResourceManager.GetString("domainservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable.
        /// </summary>
        public static string editable {
            get {
                return ResourceManager.GetString("editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel import and export.
        /// </summary>
        public static string excelimportexport {
            get {
                return ResourceManager.GetString("excelimportexport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string features {
            get {
                return ResourceManager.GetString("features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework.
        /// </summary>
        public static string framework {
            get {
                return ResourceManager.GetString("framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length.
        /// </summary>
        public static string maximumlength {
            get {
                return ResourceManager.GetString("maximumlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length.
        /// </summary>
        public static string minimumlength {
            get {
                return ResourceManager.GetString("minimumlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace Prefix.
        /// </summary>
        public static string namespaceprefix {
            get {
                return ResourceManager.GetString("namespaceprefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string nextstep {
            get {
                return ResourceManager.GetString("nextstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission service.
        /// </summary>
        public static string permissionservice {
            get {
                return ResourceManager.GetString("permissionservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string query {
            get {
                return ResourceManager.GetString("query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string regex {
            get {
                return ResourceManager.GetString("regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string repository {
            get {
                return ResourceManager.GetString("repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate service sharing permissions.
        /// </summary>
        public static string separateservicesharingpermissions {
            get {
                return ResourceManager.GetString("separateservicesharingpermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimplifiedDDD.
        /// </summary>
        public static string simplifiedDDD {
            get {
                return ResourceManager.GetString("simplifiedDDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StandardDDD.
        /// </summary>
        public static string standardDDD {
            get {
                return ResourceManager.GetString("standardDDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image.
        /// </summary>
        public static string uploadimage {
            get {
                return ResourceManager.GetString("uploadimage", resourceCulture);
            }
        }
    }
}
